# nginx/nginx.conf

# 1. Definimos nuestro sistema backend (Django + Gunicorn)
# El nombre 'web' debe coincidir con el nombre del servicio en docker-compose
upstream django_v1 {
    server web_django:8000;
}

upstream flask_v2 {
    server pagos_flask:5000;
}

server {
    listen 80;

    # RUTA VIEJA: Sigue yendo a Django
    location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # RUTA NUEVA: Estrangulamos la función de compra y la mandamos a Flask
    location /api/v2/comprar {
        proxy_pass http://flask_v2;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

    # Nota Arquitectónica: En el futuro, aquí agregaremos una nueva
    # regla 'location /api/v2/' que apuntará a nuestro microservicio Flask
    # para ejecutar el Strangler Pattern.
